### ISSUE TITLE
All tokens getting phone verification locked

### ISSUE THREAD

**Issue by VenomRaiden** [Vinyzu/DiscordGenerator#64] opened 2022-09-21 19:45 UTC
For some reason no matter what mode i try the tokens always gets locked

**Comment by Vinyzu** [comment] 2022-09-22 15:18
What proxy provider are you using? Im using creativeproxies and i have a 100% unlock rate

**Comment by FuckingToasters** [comment] 2022-09-22 19:46
> For some reason no matter what mode i try the tokens always gets locked

same, worked fine with the older version. token becomes locked when the script try to confirm mail

**Comment by Vinyzu** [comment] 2022-09-22 19:48
Seems like email cinfirmation locks token...
@FuckingToasters can you check if it locke without email confirmation?

**Comment by FuckingToasters** [comment] 2022-09-22 19:54
> Seems like email cinfirmation locks token... @FuckingToasters can you check if it locke without email confirmation?

It generate a unlocked token, add the birthdate and then, when using confirm mail option after some time the account is phone locked. when running it without mail verification the account don't become termed (browser closes, new browser open and it print this to the console: `Successfully Generated Account! Closing Browser...`)

E-Mail Verification worked fine in the older version without the Botright implementation.

**Comment by Vinyzu** [comment] 2022-09-22 20:09
Ok thanks, ill see

**Comment by FuckingToasters** [comment] 2022-09-22 20:18
> Ok thanks, ill see

After a few more debugging i noticed that i lock the token a few seconds after it print confirming mail... and after te token got locked it start to verify the mail thus resulting in a account, which is phne locked and mail verified.

**Comment by Vinyzu** [comment] 2022-09-23 05:31
I think the lock is because of the mail request, ill check later

**Comment by FuckingToasters** [comment] 2022-09-23 05:39
> I think the lock is because of the mail request, ill check later

I changed the tempmail stuff to IMAP locally because i thought that the issue is tempmail.lol but don't seem like it. even with imap in the new version the account becomes phone locked while thus wasn't the case in the old version.

**Comment by Vinyzu** [comment] 2022-09-23 14:22
> > I think the lock is because of the mail request, ill check later
> 
> I changed the tempmail stuff to IMAP locally because i thought that the issue is tempmail.lol but don't seem like it. even with imap in the new version the account becomes phone locked while thus wasn't the case in the old version.

Yes, as i said its cause of the Mail request. Dislocks sends a request to discord saying "Hey here is my email: ..." and i think playwright requests can be detected so discord detecs them and locks the token.

**Comment by Vinyzu** [comment] 2022-09-23 17:28
@FuckingToasters 
test if its fixxed in https://github.com/Vinyzu/DiscordGenerator/commit/03f861b78deb19567f44ad6b88d37aef51395d6f

**Comment by FuckingToasters** [comment] 2022-09-23 21:10
> @FuckingToasters test if its fixxed in [03f861b](https://github.com/Vinyzu/DiscordGenerator/commit/03f861b78deb19567f44ad6b88d37aef51395d6f)

It not rly fixed it:
The Bot don't automatically close th popup on the image below so i get the error below the first image:
![grafik](https://user-images.githubusercontent.com/94435104/192056942-1df290c9-e26e-4536-a29a-2bd99103b8f8.png)
```
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[class *= "fieldButton-14lHvK"] >> nth=1" to be visible
============================================================
```

After it print `Claiming Account...` & `Verifiyng Mail` & `Confirming Mail` Nothing happen so when i then close the popup from the screenshot above manually, the popup below show up:
![grafik](https://user-images.githubusercontent.com/94435104/192056964-8b549c3f-22ba-4e41-9b2b-78558e9285ce.png)

**Comment by Vinyzu** [comment] 2022-09-24 09:19
Ok thanks ill see

**Comment by CTB64YT** [comment] 2022-09-24 18:58
same thing is happening too me, i put my proxies, and it just doesnt use it it just crashes.

**Comment by FuckingToasters** [comment] 2022-09-27 09:13
It's maybe because of the domains. Is dottrick or plusstrick for Gmail's blocked by DIscord btw.?

**Comment by Vinyzu** [comment] 2022-09-27 12:44
> It's maybe because of the domains. Is dottrick or plusstrick for Gmail's blocked by DIscord btw.?

I think after 7-10 it gets blocked

**Comment by Vinyzu** [comment] 2022-09-30 16:09
Fixxed in v2.3: https://github.com/Vinyzu/DiscordGenerator/commit/d14852788b70724a05d93415fb965c2686c1c2aa

The issue is getting kinda confusing so if you still have issue make a new clean issue.

**Closed by Vinyzu** 2022-09-30 16:09 UTC
Labels: bug, enhancement
